config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destory'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'




  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

  	resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

# POST /votes => 'VotesController#create'

# POST /posts/3/vote => 'PostsController#vote'
# POST /comments/4/vote => 'CommentsController#vote'

app/models/post.rb
class Post < ActiveRecord::Base
	include Voteable
	include Sluggable

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	belongs_to :user #1:M
	has_many :comments 
	has_many :post_categories
	has_many :categories, through: :post_categories 

	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :url, presence: true, uniqueness: true
	validates_presence_of :categories
	validates_presence_of :image, :unless => :image_remote_url?, :message => " or Image URL can't be blank"

	sluggable_column :title

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]


	def image_remote_url=(url_value)
	    self.image = URI.parse(url_value) unless url_value.blank?
	    super
 	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update]



  def index
  	@posts = Post.all.sort_by{|x| x.total_votes}.reverse


    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml { render xml: @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json { render json: @post }
      format.xml { render xml: @post }
    end
   end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
  end
end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "This post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
        flash[:notice] = 'Your vote was counted.'
      else
        flash[:error] = 'You can only vote on a post once.'
      end
        redirect_to :back
      end
    format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, :image, :image_remote_url, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def correct_user
    access_denied unless logged_in? and (current_user == @post.user || current_user.admin?)
    
    #can code as well, access_denied if !logged_in  || (logged_in? and current_user != @post.user)
  end

end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='well'>
	<%= form_for @post, html: { multipart: true } do |f| %>
	<div class='control-group'>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class='control-group'>
		<%= f.label :url %>
		<%= f.text_field :url %>
	</div>

	<div class="control-group">
	    <%= f.label :image, 'Upload an image' %>
	    <%= f.file_field :image, class: "control-group" %>
  	</div>

  	<div class="form-group">
	   <%= f.label :Or_Add_Image_Upload_Via_URL %>
	   <%= f.text_field :image_remote_url,  class: "form-control" %>
  	</div>

	<div class='control-group'>
		<%= f.label :description %>
		<%= f.text_area :description, rows: 5 %>
	</div>
	<div class='control-group'>
		<%= f.label "Categories" %>
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
		<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
		<% end %>
	</div>
	<%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">

	<div class='span0 well text-center'>

		<%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
		<i class='icon-arrow-up'></i>
		<% end %>

		<br/>
		<span id='post_<%=post.slug%>_votes'><%= post.total_votes %> votes</span>
		<br/>

		<%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
		<i class='icon-arrow-down'></i>
		<% end %>


	</div>




		<div class="span8 well">
			<span class="icon-tags"></span>
			<%= render post.categories %>
			<h4><%= link_to post.title, fix_url(post.url), :target => "_blank" %></h4> 
			<%= image_tag post.image.url(:medium), class: "img-polaroid" %>
			<p><%= post.description %></p>
			<p>
				<span class='quiet'>posted by</span>  <%= link_to post.user.username, user_path(post.user) %>
				<small>at <%= display_datetime(post.created_at) %></small>
			</p>
			<small>
				<span class="label label-warning"><i class="icon-fire"></i>
        			<%= link_to("#{post.comments.size} comments", post_path(post)) %> 
        		</span>
			</small>
		</div>
	</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create new post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? && (@post.user == current_user || current_user.admin?) %>
	<p class='pull-right'>
		<span class="icon-edit"></span>[<%= link_to 'edit this post', edit_post_path(@post)%>]
	</p>
<% end %>

<!--! if @post.user || current_user.admin? post creator or admin can only see edit link and preform edit action on posts-->


<p>
<%= render @post.categories %>
</p>

<% render 'shared/content_title', title: @post.title %>

<%= image_tag @post.image.url, :size => "600x600", class: "img-rounded" %>

<p>
	<%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
	<%= form_for [@post, @comment] do |f| %>
	<%= render 'shared/errors', obj: @comment %>
		<div class='control-group'>
			<span class="icon-pencil"></span>
			<%= f.label :body, 'Leave a comment' %>
			
			<%= f.text_area :body, rows: 3, class: 'span4' %>
		</div>
		<%= f.submit "Create comment", class: "btn btn-info" %>
	<% end %>
<% end %>

<h5>Comments</h5>

<% @post.reload.comments.each do |comment| %>
<%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
$("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes")
<% else %>

 alert('You can only vote on this post once.');

<% end %>